---
- name: Install and configure web servers
  hosts: webservers
  roles:
    - role: apache
    - role: php
    - role: php-mysql
  tasks:
    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes
