---
- name: Deploy Web Servers
  hosts: webservers
  become: yes
  tags: webserver
  
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      tags: apache
    
    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes
      tags: apache

- name: Deploy Nginx
  hosts: nginx
  become: yes
  tags: nginx
  
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      tags: nginx
    
    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
      tags: nginx

- name: Common Tasks for All Servers
  hosts: all
  become: yes
  tags: common
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: update
    
    - name: Install common packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - git
      tags: packages
