---
env_name: production
enable_nginx_lb: true
enable_apache_lb: false
load_balancer_is_required: true

mysql_root_password: "Alph@Poison4607"
mysql_databases:
  - name: tooling
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: tooling_user
    host: "%"
    password: "Alph@Poison4607"
    priv: "tooling.*:ALL,GRANT"

nginx_upstream_servers:
  - "web1-prod:80"
  - "web2-prod:80"
